# app/config/security.yml
security:
    encoders:
        Chat\ChatBundle\Entity\User:
            algorithm: bcrypt
    providers:
        main_provider:
            entity: { class: Chat\ChatBundle\Entity\User, property: username}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main_firewall:
            anonymous: true
            pattern: ^/
            form_login:
                provider: main_provider
                login_path: /user/login
                check_path: /user/login-check
                default_target_path: /chat
                csrf_provider: security.csrf.token_manager
            logout:
                path: /user/logout
                target: /
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    access_control:
        - { path: ^/user/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/sign-up$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/chat, roles: ROLE_USER }